name: Cloud Build Theme

on:
  workflow_dispatch: # 允许我们在网页上手动点击触发打包

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖并开始打包
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install --legacy-peer-deps
          npm run build

      - name: 导出成品打包
        uses: actions/upload-artifact@v4
        with:
          name: EZ-Theme-Dist # 导出的压缩包名字
          path: dist/        # 将打包出来的 dist 文件夹变成 zip
